server:
  port: 9000

spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin

logging:
  config: classpath:log4j2-spring.xml

eureka:
  instance:
    appname: ${spring.application.name}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@10.3.212.35:${server.port}/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
  server:
    peer-node-read-timeout-ms: 500